// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationWorker.Data;

#nullable disable

namespace ReservationWorker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317021426_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationWorker.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RestaurantTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("ReservationWorker.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("ReservationWorker.Entities.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("table_number");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("restaurant_tables", (string)null);
                });

            modelBuilder.Entity("ReservationWorker.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAnyTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasMapLayout")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TotalCapacity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("ReservationWorker.Entities.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("TimeSlots", (string)null);
                });

            modelBuilder.Entity("ReservationWorker.Entities.RestaurantTable", b =>
                {
                    b.HasOne("ReservationWorker.Entities.Sector", "Sector")
                        .WithMany("Tables")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("ReservationWorker.Entities.Sector", b =>
                {
                    b.HasOne("ReservationWorker.Entities.Restaurant", null)
                        .WithMany("Sectors")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservationWorker.Entities.TimeSlot", b =>
                {
                    b.HasOne("ReservationWorker.Entities.Sector", null)
                        .WithMany("TimeSlots")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservationWorker.Entities.Restaurant", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("ReservationWorker.Entities.Sector", b =>
                {
                    b.Navigation("Tables");

                    b.Navigation("TimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
