// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationWorker.Data;

#nullable disable

namespace ReservationWorker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312142816_AddFloorManagement")]
    partial class AddFloorManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationWorker.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_phone");

                    b.Property<int>("GuestCount")
                        .HasColumnType("integer")
                        .HasColumnName("guest_count");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_date");

                    b.Property<Guid>("RestaurantTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_table_id");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantTableId");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("ReservationWorker.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("restaurants");
                });

            modelBuilder.Entity("ReservationWorker.Entities.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<int>("TableNumber")
                        .HasColumnType("integer")
                        .HasColumnName("table_number");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("restaurant_tables");
                });

            modelBuilder.Entity("ReservationWorker.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowAnyTable")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_any_table");

                    b.Property<bool>("HasMapLayout")
                        .HasColumnType("boolean")
                        .HasColumnName("has_map_layout");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("sectors");
                });

            modelBuilder.Entity("ReservationWorker.Entities.Reservation", b =>
                {
                    b.HasOne("ReservationWorker.Entities.RestaurantTable", "RestaurantTable")
                        .WithMany()
                        .HasForeignKey("RestaurantTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("ReservationWorker.Entities.RestaurantTable", b =>
                {
                    b.HasOne("ReservationWorker.Entities.Sector", "Sector")
                        .WithMany("Tables")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("ReservationWorker.Entities.Sector", b =>
                {
                    b.HasOne("ReservationWorker.Entities.Restaurant", "Restaurant")
                        .WithMany("Sectors")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("ReservationWorker.Entities.Restaurant", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("ReservationWorker.Entities.Sector", b =>
                {
                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
